apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: aus.alpha.example.org
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: alpha.example.org
  # version name to use for REST API: /apis/<group>/<version>
  version: v1
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: aus
    # singular name to be used as an alias on the CLI and for display
    singular: au
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: AU
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - au
  validation:
   # openAPIV3Schema is the schema for validating custom objects.
    openAPIV3Schema:
      properties:
        spec:
          properties:
            operation:
              type: string
              # More operations could be put here
              pattern: '^(update)$'

